services:
  postgres:
    image: postgres:16.3
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      # POS_DB_USER: ${POS_DB_USER}
      # POS_DB_PASSWORD: ${POS_DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 20s
      timeout: 3s
      retries: 3
      start_period: 5s

  backend:
    build:
      context: ./core-pos
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SCHAFFBAR_DS_URL: "jdbc:postgresql://postgres:5432/${POSTGRES_DB}"
      SCHAFFBAR_DS_USERNAME: ${POSTGRES_USER}
      SCHAFFBAR_DS_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_PROFILES_ACTIVE: "prod"
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    build:
      context: ../schaffbar-portal
      args:
        FRONTEND_ENV: ${FRONTEND_ENV}
    depends_on:
      - backend
    ports:
      - 8080:8080

volumes:
  postgres_data:
